repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: detect-private-key
  - id: check-yaml
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-case-conflict
  - id: check-symlinks
  - id: check-merge-conflict
  - id: destroyed-symlinks
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: name-tests-test
    args: [--pytest-test-first]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint-fix
    name: Format Markdown files
    args: [--disable, MD013]  # Ignore line length
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.1
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
    files: ^.*\.toml$
